function docs = referenceDocuments()
%REFERENCEDOCUMENTS  Every document this tool's numbers rest on.
%   docs = data.referenceDocuments() returns a struct array, one row per
%   document, with the citation, what the tool takes from it, and the file
%   name a local copy would have.
%
%   WHY A LIST AND NOT A BUNDLE. The Help menu was specified as "opening
%   the bundled PDFs" (GUI2_SPEC.md Sec. 3). It cannot be. Nine of these
%   documents are not ours to redistribute -- every NAS/NASM sheet carries
%   "COPYRIGHT ... Aerospace Industries Association ... ALL RIGHTS
%   RESERVED", the DABJ course book carries a copyright notice and
%   restrictions, and the Heli-Coil bulletin is vendor material -- and
%   references/ is gitignored twice over precisely so none of them can be
%   published by accident. Shipping them inside a distributed .exe would
%   be an infringement, and the copyrighted ones are exactly the sheets
%   the hardware catalogue is transcribed from.
%
%   So the tool ships the CITATIONS, which are facts and are the part that
%   carries traceability, and opens a local copy only where the analyst
%   already has one. An analyst asking "where did this allowable come
%   from?" gets an answer either way; only the convenience of the click
%   depends on the file being present.
%
%   HEADLESS ON PURPOSE. gui2.ReferencesView renders this, but the list is
%   data rather than layout: it is the single place the citations live, it
%   is testable without building a GUI, and a report could use it too.
%
%   Fields:
%     Key             short id, stable across renames of the file
%     Title           document title as printed on it
%     Publisher       issuing body
%     Year            edition/revision year as a string ("" if not dated)
%     Role            "Governing" | "Supplemental" | "Hardware data" |
%                     "Validation" | "Background"
%     UsedFor         what THIS tool takes from it, in one line
%     File            expected file name of a local copy ("" if none)
%     Redistributable logical -- may this ship inside the packaged tool
%
%   ROLE FOLLOWS CLAUDE.md's DOCUMENT HIERARCHY, and the distinction is
%   not cosmetic: NASA-STD-5020B governs; a supplement is cited only where
%   5020B itself relies on it for a formula it does not print; and the
%   DABJ course book is VALIDATION ONLY and must never be cited as a
%   governing equation. A reader of this list should be able to see that
%   ordering without knowing the rule already.
%
%   Tests: tests/tReferenceDocuments.m.

docs = [ ...
    row("NASA-STD-5020B", ...
        "Requirements for Threaded Fastening Systems in Spaceflight Hardware", ...
        "NASA", "2021", "Governing", ...
        "The governing standard. Preload, tension, shear, separation, " + ...
        "interaction, slip, the Fig. 8 separation-before-rupture gate, " + ...
        "and every factor-of-safety and fitting-factor rule.", ...
        "2021-08-06-nasa-std-5020b_final.pdf", true), ...
    row("NASA TM-106943", ...
        "Preloaded Joint Analysis Methodology for Space Flight Systems (Chambers)", ...
        "NASA", "1995", "Supplemental", ...
        "Formulas 5020B uses but does not print: the CTE-mismatch thermal " + ...
        "preload term (Eq. 10), the joint-stiffness harmonic mean (Eq. 34), " + ...
        "and the member-strength checks -- bearing, tear-out and thread shear.", ...
        "TM-106943.pdf", true), ...
    row("NASA RP-1228", ...
        "Fastener Design Manual (Barrett)", ...
        "NASA", "1990", "Supplemental", ...
        "Background on fastener selection and preload practice. Cited only " + ...
        "where 5020B relies on it.", ...
        "RP-1228.pdf", true), ...
    row("NASM33537", ...
        "Insert, Screw Thread -- Helical Coil", ...
        "Aerospace Industries Association", "2025", "Hardware data", ...
        "Tapped-hole and STI geometry for the 30 seeded helical-coil " + ...
        "inserts, including the Table IV pitch diameters.", ...
        "NASM33537.pdf", false), ...
    row("NAS1351", ...
        "Screw, Cap, Socket Head, Undrilled and Drilled -- UNRF", ...
        "Aerospace Industries Association", "2009", "Hardware data", ...
        "Fine-thread socket head cap screw geometry and the Table III " + ...
        "length ladder for the seeded bolt catalogue.", ...
        "NAS1351.PDF", false), ...
    row("NAS1352", ...
        "Screw, Cap, Socket Head, Undrilled and Drilled -- UNRC", ...
        "Aerospace Industries Association", "2009", "Hardware data", ...
        "The coarse-thread half of the same catalogue.", ...
        "NAS1352.PDF", false), ...
    row("NASM21042", ...
        "Nut, Self-Locking, 450 F, Reduced Hexagon, Reduced Height, Ring Base", ...
        "Aerospace Industries Association", "2026", "Hardware data", ...
        "Nut geometry and rated loads. Carries an essential-usage " + ...
        "advisory recorded on every seeded entry.", ...
        "NASM21042.pdf", false), ...
    row("NAS1291", ...
        "Nut, Self-Locking, Hexagon, Regular Height, 450 F", ...
        "Aerospace Industries Association", "2025", "Hardware data", ...
        "The second seeded nut family (A286 CRES only -- Rev 16 struck " + ...
        "out the steel variants).", ...
        "NAS1291.pdf", false), ...
    row("NAS620", ...
        "Washer, Flat, Reduced Outside Diameter", ...
        "Aerospace Industries Association", "2013", "Hardware data", ...
        "Reduced-OD washer geometry (16 seeded sizes).", ...
        "NAS620.pdf", false), ...
    row("NAS1149", ...
        "Washer, Flat", ...
        "Aerospace Industries Association", "2008", "Hardware data", ...
        "Standard-OD washer geometry (42 seeded sizes).", ...
        "NAS1149.pdf", false), ...
    row("FF-S-86F", ...
        "Federal Specification: Screw, Cap, Socket Head", ...
        "U.S. General Services Administration", "2020", "Hardware data", ...
        "Table VII rated tensile loads, the source of every seeded " + ...
        "bolt-spec ultimate and yield rating.", ...
        "FF-S-86F.pdf", true), ...
    row("Heli-Coil TB 68-2", ...
        "Tensile Strength of Threaded Insert Assembly (Technical Bulletin 68-2)", ...
        "Stanley Engineered Fastening", "", "Hardware data", ...
        "Insert pull-out strength. Publishes charts rather than tables, " + ...
        "which is why no insert strength is seeded and the tool computes " + ...
        "the engagement area instead.", ...
        "Tensile_Strength_HC68-2_rev4.pdf", false), ...
    row("DABJ course book", ...
        "Design and Analysis of Bolted Joints -- course book, Section 9 worked example", ...
        "Course material", "2025", "Validation", ...
        "THE ANSWER KEY, and nothing else. Its Section 9 worked example " + ...
        "and Example 8-b pin this tool's numbers. Never cited as a " + ...
        "governing equation -- see CLAUDE.md's document hierarchy.", ...
        "DABJ_course_book-Dec2025-2.pdf", false), ...
    row("SAND2008-0371", ...
        "Bolted Joint Analysis (Sandia)", ...
        "Sandia National Laboratories", "2008", "Background", ...
        "Corroborating treatment of preload scatter and joint stiffness. " + ...
        "Not cited for any implemented equation.", ...
        "SAND2008-0371.pdf", true), ...
    row("NASA TM-108377", ...
        "A Method of Analysis for Bolted Joints", ...
        "NASA", "", "Background", ...
        "Corroborating background. Not cited for any implemented equation.", ...
        "NASA TM-108377.pdf", true)];
end

% ---- Local helpers --------------------------------------------------------
function d = row(key, title, publisher, year, role, usedFor, file, redist)
%ROW  One reference document.
d = struct( ...
    "Key",             string(key), ...
    "Title",           string(title), ...
    "Publisher",       string(publisher), ...
    "Year",            string(year), ...
    "Role",            string(role), ...
    "UsedFor",         string(usedFor), ...
    "File",            string(file), ...
    "Redistributable", logical(redist));
end
