function h = bulkHeaders(vars)
%BULKHEADERS  Bulk table column names -> the headers an export shows.
%   h = report.bulkHeaders(vars) maps engine.analyzeBulk and
%   report.bulkJointSummary variable names to readable headers. A margin
%   column takes its check's name as the Results page shows it; loads carry
%   their unit. A name not listed falls back to gui.MarginView.headerText,
%   so a new column still gets a readable header.
%
%   The bulk template colours margin columns by these headers (its hidden
%   Lists sheet names them); tExportTemplates checks the two agree.
arguments
    vars (1,:) string
end
map = dictionary( ...
    ["ElementId", "JointName", "Joint", "LoadCase", "Axial", "Shear", ...
     "TensionUlt", "TensionYield", "ShearUlt", "ShearTearout", "Bearing", ...
     "BearingUnderHead", "BoltThreadShear", "NutStrength", "InsertInternal", ...
     "InsertExternal", "Separation", "Slip", "SepBeforeRupture", ...
     "InteractionR", "TappedParent", "WorstMargin", "GoverningCheck", ...
     "Error", "Note", "Warnings", "Analyses", "Failing", "Errors", ...
     "WorstElement", "WorstLoadCase"], ...
    ["Element", "Joint", "Joint", "Load Case", "Axial (lbf)", "Shear (lbf)", ...
     "Tension-Ultimate", "Tension-Yield", "Shear-Ultimate", "Shear-tearout", "Bearing", ...
     "Bearing-under-head", "Bolt-thread shear", "Nut strength", "Insert internal-thread", ...
     "Insert external-thread", "Separation", "Slip", "Separation-before-rupture", ...
     "Interaction R (≤ 1)", "Tapped-hole parent-thread", "Worst Margin", "Governing Check", ...
     "Error", "Note", "Warnings", "Analyses", "Failing Analyses", "Errors", ...
     "Worst Element", "Worst Load Case"]);
h = strings(1, numel(vars));
for i = 1:numel(vars)
    if isKey(map, vars(i))
        h(i) = map(vars(i));
    else
        h(i) = string(gui.MarginView.headerText(vars(i)));
    end
end
end
