function L = exportLayout()
%EXPORTLAYOUT  Where report.writeSingleJointWorkbook writes, by named range.
%   L.<Name> has Sheet, TopLeft, Rows, Cols and Ref ("Slide!$A$5:$B$19").
%   The names and refs match the named ranges in templates/export_single.xlsx
%   (built by tools/make_export_templates.py); tExportTemplates checks that.
L = struct( ...
    'SlideTitle',        spec("SlideTitle",        "Slide",  "A", 1,  "A", 1), ...
    'SlideSubtitle',     spec("SlideSubtitle",     "Slide",  "A", 2,  "A", 2), ...
    'SlideVerdictClass', spec("SlideVerdictClass", "Slide",  "I", 1,  "I", 1), ...
    'SlideInputs',       spec("SlideInputs",       "Slide",  "A", 5,  "B", 19), ...
    'SlideMargins',      spec("SlideMargins",      "Slide",  "D", 5,  "G", 19), ...
    'SlideScope',        spec("SlideScope",        "Slide",  "A", 21, "A", 21), ...
    'DetailRows',        spec("DetailRows",        "Detail", "A", 2,  "F", 16), ...
    'AboutRows',         spec("AboutRows",         "About",  "A", 2,  "B", 25));
end

function s = spec(name, sheet, c0, r0, c1, r1)
if r0 == r1 && c0 == c1
    ref = sprintf("%s!$%s$%d", sheet, c0, r0);
else
    ref = sprintf("%s!$%s$%d:$%s$%d", sheet, c0, r0, c1, r1);
end
s = struct('Name', name, 'Sheet', sheet, 'TopLeft', c0 + r0, ...
    'Rows', r1 - r0 + 1, 'Cols', double(char(c1)) - double(char(c0)) + 1, ...
    'Ref', ref);
end
