function chapters = userGuideChapters()
%USERGUIDECHAPTERS  The user guide's text, as data.
%   chapters = report.userGuideChapters() returns a struct array with
%   Title and Body (a string array of paragraphs), which report.userGuide
%   renders to PDF.
%
%   SEPARATE FROM THE RENDERER so the prose can be read and edited as a
%   document rather than picked out from between DOM calls, and so tests
%   can assert on what the guide says without building a PDF. Same split
%   as data.referenceDocuments.
%   Prose in one place rather than interleaved with DOM calls, so it can
%   be read and edited as a document. Every claim here is about behaviour
%   the tests pin; if one stops being true, it is a bug in the tool or a
%   bug in this text, and both are worth finding.
chapters = [ ...
    chapter("What this tool does", [ ...
        "This tool computes margins of safety for preloaded bolted " + ...
        "joints to NASA-STD-5020B. It runs one joint at a time from the " + ...
        "Single Joint pages, or many at once from the Bulk pages using " + ...
        "forces exported from an FE model."; ...
        "It reports all fifteen checks the engine computes: fourteen " + ...
        "margin rows plus the Figure 8 separation-before-rupture gate, " + ...
        "which selects which equation prices the bolt load rather than " + ...
        "carrying a margin of its own."; ...
        "Every result names the equation behind it. Where an input is " + ...
        "missing the check reports Not evaluated rather than a number -- " + ...
        "the tool never fills a gap with an assumption you did not make."]), ...
    chapter("Getting around", [ ...
        "The rail on the left holds every page, in four groups. SETUP is " + ...
        "the joint and the conditions it sees. SINGLE JOINT is one " + ...
        "analysis and the joints you have saved in this case. BULK is the " + ...
        "FE workflow. REFERENCE is the hardware library."; ...
        "A marker beside a rail entry means that page has something to " + ...
        "say -- results that are out of date with respect to an edit, or " + ...
        "data loaded and waiting."; ...
        "The title bar carries the case file and an asterisk when there " + ...
        "is unsaved work. File > Save writes the case; the hardware " + ...
        "library is NOT part of it and is saved separately."]), ...
    chapter("Setting up a joint", [ ...
        "Project records who is running the analysis and what it is for. " + ...
        "It is never analysed -- it travels with the case so a result can " + ...
        "be attributed later."; ...
        "Factors carries the factors of safety and fitting factors. The " + ...
        "built-in NASA-STD-5020B preset is the starting point; a program " + ...
        "that levies its own values can be saved as a user preset."; ...
        "Temp Loads is GLOBAL -- assembly, hot and cold temperatures " + ...
        "apply to every joint in the case, not just the one on screen. " + ...
        "The engine works in degrees Celsius internally because CTE data " + ...
        "is per degree Celsius; everything else is US customary."; ...
        "Joint Config is the substantial one: bolt, materials, the flange " + ...
        "stack, the threaded member, and the applied loads. Fields " + ...
        "required before an analysis can run are marked, and the Analyze " + ...
        "button stays disabled until every one of them is filled. It " + ...
        "tells you which are outstanding rather than simply refusing."]), ...
    chapter("Reading the results", [ ...
        "The Results page shows every check as a row: the margin, its " + ...
        "status, and the equation that produced it. Select a row to see " + ...
        "the working behind it."; ...
        "PASS and FAIL mean what they say. NOT EVALUATED means an input " + ...
        "the check needs was not supplied -- it is not a pass, and the " + ...
        "row says which input is missing. A joint is only clean when " + ...
        "every row you rely on has been evaluated."; ...
        "Two rows are not margins and are marked accordingly. INTERACTION " + ...
        "is a criterion: NASA-STD-5020B states it as R <= 1 rather than " + ...
        "as a margin, so the row carries the ratio R. " + ...
        "SEPARATION-BEFORE-RUPTURE reports Assured or Not assured -- it " + ...
        "selects a branch, and not-assured is the conservative one, not a " + ...
        "failure."; ...
        "Analysis decisions, below the table, states which branch the " + ...
        "Figure 8 gate took and which allowable governed. Warnings sit " + ...
        "beside it and are never margins: a preload close to yield or a " + ...
        "bolt too short for its stack is worth knowing whatever the " + ...
        "margins say."; ...
        "Export writes the same rows to a workbook, and Report writes a " + ...
        "PDF stamped with the tool version and the time it was run."]), ...
    chapter("Analysing many joints", [ ...
        "Defined Joints holds the joints saved in this case. Build one on " + ...
        "Joint Config and add it here; the list travels inside the case " + ...
        "file."; ...
        "Element Mapping ties FE element IDs to those joints. Element " + ...
        "Forces imports the forces themselves, one load case per sheet, " + ...
        "and resolves them to per-bolt tension and shear."; ...
        "Bulk Analysis runs every mapped element and gives one row each, " + ...
        "with the worst margin and the check that governed it. The " + ...
        "interaction ratio has its own column, because it is not " + ...
        "comparable to a margin and must not be sorted alongside one."]), ...
    chapter("The hardware library", [ ...
        "Materials & Hardware holds the materials, bolts, bolt specs, " + ...
        "nuts, washers and inserts the tool knows about. It is shared by " + ...
        "every case and is not saved in the case file."; ...
        "Baseline entries ship with the tool and are read-only. Every one " + ...
        "carries the source its values came from -- which standard, which " + ...
        "table -- and that citation is on screen for every row. It is the " + ...
        "first thing to check when a number is not what you expected."; ...
        "To change a baseline value, select it and use Duplicate as " + ...
        "Custom: the form opens pre-filled, you edit what needs changing, " + ...
        "and you supply a source for the new numbers. A citation is " + ...
        "required on every entry the tool writes."; ...
        "Custom entries are yours and are saved separately with Save " + ...
        "Library. A corrected baseline in a later release still reaches " + ...
        "you: the shipped values are re-merged underneath your own each " + ...
        "time the tool starts."]), ...
    chapter("What this tool does not do", [ ...
        "It does not size bolts. The sweep exists in the engine and can " + ...
        "be driven from the command line, but there is no screen for it."; ...
        "It does not switch units. Everything is US customary, with " + ...
        "temperatures in degrees Celsius."; ...
        "It does not decide whether friction may be relied on, whether a " + ...
        "joint is separation-critical, or what factors your programme " + ...
        "levies. Those are yours, and the tool warns where an entry sits " + ...
        "outside what the standard permits without test substantiation."; ...
        "It analyses one bolt -- the most loaded one -- not a pattern. " + ...
        "The joint-level slip check takes joint totals you supply, " + ...
        "because they are not simply the per-bolt loads multiplied by the " + ...
        "bolt count."]), ...
    chapter("Where the numbers come from", [ ...
        "Help > References lists every document this tool's numbers rest " + ...
        "on, what it is used for, and its role: NASA-STD-5020B governs, a " + ...
        "supplement is cited only where the standard itself relies on it, " + ...
        "and the course-book worked example is validation only and is " + ...
        "never a source of equations."; ...
        "Most of those documents are copyrighted and are not shipped with " + ...
        "the tool. The citation is always there; point the References " + ...
        "window at your own folder of standards and it will open your " + ...
        "copies too."; ...
        "Help > About states the version. Quote it when reporting " + ...
        "anything -- every report and export carries it for the same " + ...
        "reason."])];
end

function c = chapter(titleText, body)
c = struct("Title", string(titleText), "Body", body);
end
